// <auto-generated />
using FootballWarsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballWarsAPI.Migrations
{
    [DbContext(typeof(FootballContext))]
    [Migration("20231012160023_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballWarsAPI.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Club");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img_Name = "FCBarcelonaImg",
                            LeagueId = 2,
                            Name = "FC Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            Img_Name = "RealMadridImg",
                            LeagueId = 2,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 3,
                            Img_Name = "ManchesterCityImg",
                            LeagueId = 1,
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 4,
                            Img_Name = "ArsenalImg",
                            LeagueId = 1,
                            Name = "Arsenal FC"
                        },
                        new
                        {
                            Id = 5,
                            Img_Name = "InterImg",
                            LeagueId = 3,
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = 6,
                            Img_Name = "ACMilanImg",
                            LeagueId = 3,
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = 7,
                            Img_Name = "FCBayernImg",
                            LeagueId = 4,
                            Name = "FC Bayern Munchen"
                        },
                        new
                        {
                            Id = 8,
                            Img_Name = "DortmundImg",
                            LeagueId = 4,
                            Name = "Dortmund"
                        },
                        new
                        {
                            Id = 9,
                            Img_Name = "ParisImg",
                            LeagueId = 5,
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("FootballWarsAPI.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img_Name = "PremierImg",
                            Name = "Premier League"
                        },
                        new
                        {
                            Id = 2,
                            Img_Name = "LaligaImg",
                            Name = "Laliga"
                        },
                        new
                        {
                            Id = 3,
                            Img_Name = "SerieAImg",
                            Name = "Serie A"
                        },
                        new
                        {
                            Id = 4,
                            Img_Name = "BundesligaImg",
                            Name = "Bundesliga"
                        },
                        new
                        {
                            Id = 5,
                            Img_Name = "Ligue1Img",
                            Name = "Ligue 1"
                        });
                });

            modelBuilder.Entity("FootballWarsAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Img_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            Img_Name = "FrenkieImg",
                            Name = "Frenkie De Jong"
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 2,
                            Img_Name = "LukaImg",
                            Name = "Luka Modric"
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 3,
                            Img_Name = "ErlingImg",
                            Name = "Erling Haaland"
                        },
                        new
                        {
                            Id = 4,
                            ClubId = 4,
                            Img_Name = "MartinImg",
                            Name = "Martin Odergaard"
                        },
                        new
                        {
                            Id = 5,
                            ClubId = 5,
                            Img_Name = "LautaroImg",
                            Name = "Lautaro Martinez"
                        },
                        new
                        {
                            Id = 6,
                            ClubId = 6,
                            Img_Name = "RafaelImg",
                            Name = "Rafael Leao"
                        },
                        new
                        {
                            Id = 7,
                            ClubId = 7,
                            Img_Name = "ThomasImg",
                            Name = "Thomas Muller"
                        },
                        new
                        {
                            Id = 8,
                            ClubId = 8,
                            Img_Name = "MarcoImg",
                            Name = "Marco Reus"
                        },
                        new
                        {
                            Id = 9,
                            ClubId = 9,
                            Img_Name = "KylianImg",
                            Name = "Kylian Mbappe"
                        });
                });

            modelBuilder.Entity("FootballWarsAPI.Models.Club", b =>
                {
                    b.HasOne("FootballWarsAPI.Models.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballWarsAPI.Models.Player", b =>
                {
                    b.HasOne("FootballWarsAPI.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballWarsAPI.Models.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootballWarsAPI.Models.League", b =>
                {
                    b.Navigation("Clubs");
                });
#pragma warning restore 612, 618
        }
    }
}
